# 
server {
    listen 127.0.0.1:8080;
    access_log off;
    location /api {
        stub_status;
        allow 127.0.0.1;
        deny all;
    }
}

# 
# 
log_format agent_json escape=json '{'
    '"time_local":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"request":"$request",'
    '"status":"$status",'
    '"body_bytes_sent":"$body_bytes_sent",'
    '"request_time":"$request_time",'
    '"upstream_response_time":"$upstream_response_time",'
    '"upstream_addr":"$upstream_addr"'
'}';

# 
access_log /tmp/nginx-agent-access.log agent_json;
