server {
    # Listen on localhost port 8080, dedicated for the Agent to read metrics
    listen 127.0.0.1:8080;
    
    # Disable access_log for this server block to prevent the Agent's own polling from filling up the logs
    access_log off;

    location /api {
        stub_status;
        allow 127.0.0.1;
        deny all;
    }
}
