---
name: Nginx Proxy Manager with Agent
version: dev-003
slug: nginxproxymanager_w_agent
description: Manage Nginx proxy hosts with a simple, powerful interface
url: https://github.com/raphael1688dev/addon-nginx-proxy-manager-with-agent
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:81]
startup: services
init: false
arch:
  - aarch64
  - amd64
hassio_api: true
ports:
  80/tcp: 80
  81/tcp: 81
  443/tcp: 443
map:
  - addon_config:rw
options:
  # NGINX Agent
  data_plane_key: ""
schema:
  # NGINX Agent
  data_plane_key: "str?"
backup_exclude:
  - "*/logs"
